# Generated by Django 2.2.24 on 2021-12-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='student',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
