# Generated by Django 4.0.1 on 2022-02-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('user_type', models.CharField(blank=True, max_length=255, null=True)),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email_address', models.CharField(blank=True, max_length=255, null=True)),
                ('password', models.CharField(max_length=255)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('nationality', models.CharField(blank=True, max_length=255, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('languages', models.TextField(blank=True, null=True)),
                ('height', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('gender', models.CharField(blank=True, max_length=255, null=True)),
                ('year_of_experince', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_promotion', models.IntegerField(blank=True, null=True)),
                ('identification', models.CharField(blank=True, max_length=255, null=True)),
                ('business_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('director_doc', models.CharField(blank=True, max_length=255, null=True)),
                ('facebooklink', models.CharField(blank=True, db_column='facebookLink', max_length=255, null=True)),
                ('twitterlink', models.CharField(blank=True, db_column='twitterLink', max_length=255, null=True)),
                ('instagramlink', models.CharField(blank=True, db_column='instagramLink', max_length=255, null=True)),
                ('uniquekey', models.CharField(blank=True, db_column='uniqueKey', max_length=255, null=True)),
                ('terms', models.IntegerField()),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AddVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_name', models.CharField(max_length=50)),
                ('duration', models.CharField(max_length=50)),
                ('language', models.CharField(choices=[('eng', 'English'), ('hin', 'Hindi')], max_length=6)),
                ('application_sub', models.CharField(choices=[('one', 'One'), ('two', 'Two')], max_length=6)),
                ('workout_type', models.CharField(choices=[('one', 'One'), ('two', 'Two')], max_length=6)),
                ('intensity', models.CharField(choices=[('one', 'One'), ('two', 'Two')], max_length=6)),
                ('addition_info', models.CharField(max_length=150)),
                ('video', models.FileField(upload_to='videos/')),
                ('video_teaser', models.FileField(upload_to='videosteaser/')),
                ('profile_image', models.ImageField(upload_to='profileimages/')),
                ('title_image', models.ImageField(upload_to='titleimages/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('videofile', models.FileField(null=True, upload_to='videos/', verbose_name='')),
            ],
        ),
    ]
